baseURL: https://monsoons-blog.github.io/
languageCode: en
title: Rumuuz
theme: hugo-theme-hasan

# Language Properties
defaultContentLanguage: en

languages:
  en:
      contentDir: content/
      disabled: false
      languageCode: en-US
      languageDirection: ltr
      languageName: English
      weight: 0
  ur:
      contentDir: content/ur
      disabled: false
      languageCode: ur
      languageDirection: rtl
      languageName: Urdu
      weight: 1
 
  


# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

paginate: 10

googleAnalytics: your-google-analytics-id
disqusShortname: disqus_K7fdrAybT0

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: Hasan Khan
  # Author biography
  bio: 
  # Site Description, used in HTML meat
  description: Shayari notes


  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: false
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: true
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: ' ' 

  # Extra links in navigation
  links:
    ## e.g.
    - name: Poetry
      path: /poetry
    - name: Shayari
      path: /ur
    - name: Prose
      path: /prose
    - name: Notes
      path: /notes
    - name: Translit
      path: /transliterations
    - name: Library
      path: /library
    - name: Subscribe
      path: /subscribe
    

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js
